// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv9yxiWQvrWnxk2gk1QF8fZiK0wtMpfag',
    appId: '1:759953138907:web:e9e1c33b472f46c54798fe',
    messagingSenderId: '759953138907',
    projectId: 'flutter-test-15b26',
    authDomain: 'flutter-test-15b26.firebaseapp.com',
    storageBucket: 'flutter-test-15b26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWIhvr7i7qTEdf9As0NIF0ifsodV0dWU',
    appId: '1:759953138907:android:de079ea5671d45744798fe',
    messagingSenderId: '759953138907',
    projectId: 'flutter-test-15b26',
    storageBucket: 'flutter-test-15b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvldzVB8jIG6e-cnomWcWRzY-xn0Raans',
    appId: '1:759953138907:ios:70b854ab4fc3723b4798fe',
    messagingSenderId: '759953138907',
    projectId: 'flutter-test-15b26',
    storageBucket: 'flutter-test-15b26.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvldzVB8jIG6e-cnomWcWRzY-xn0Raans',
    appId: '1:759953138907:ios:70b854ab4fc3723b4798fe',
    messagingSenderId: '759953138907',
    projectId: 'flutter-test-15b26',
    storageBucket: 'flutter-test-15b26.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
